export const people = [
  {
    name: "Christian Malheiros",
    profile: "@christianmalheiros_",
    from: "Nando em <i>Sintonia</i>",
    list: [
      "A Vida e a História de Madam C. J. Walker",
      "Paquita Salas",
      "Boca a Boca",
      "Ninguém Tá Olhando",
      "Riphagen",
      "Sintonia",
      "Rainha do Sul",
      "Coisa Mais Linda",
      "Olhos que Condenam",
      "Power",
    ],
  },
  {
    name: "Juliana Cavalcanti",
    profile: "@xulianac",
    from: "Criadora de conteúdos mara",
    list: [
      "Paquita Salas",
      "Boca a Boca",
      "Ninguém Tá Olhando",
      "A Vida e a História de Madam C. J. Walker",
      "Solteiramente",
      "Reunião de Família",
      "Peles",
      "Viagem das Garotas",
      "Ninguém Sabe que Estou Aqui",
      "Hoje Eu Quero Voltar Sozinho",
    ],
  },
  {
    name: "DOMENICA DIAS",
    profile: "@domenicadiasp",
    from: "Atriz, filha do Mano Brown",
    list: [
      "Ela Quer Tudo",
      "Estou Me Guardando para Quando o Carnaval Chegar",
      "Ritmo + Flow",
      "RuPaul’s Drag Race",
      "What Happened, Miss Simone?",
      "Next in Fashion",
      "A Morte e Vida de Marsha P. Johnson",
      "Quincy",
      "Homecoming",
      "Irmandade",
    ],
  },
  {
    name: "Andreza Delgado",
    profile: "@andrezadelgado",
    from: "Uma das criadoras do @perifacon",
    list: [
      "BoJack Horseman",
      "The Umbrella Academy",
      "The Midnight Gospel",
      "Sem Maturidade Para Isso",
      "Unbreakable Kimmy Schmidt",
      "Grace and Frankie",
      "Tuca & Bertie",
      "Um Crime para Dois",
      "Luke Cage",
      "Sintonia",
    ],
  },
  {
    name: "Danilo Mesquita",
    profile: "@_danilomesquita",
    from: "Teto em <i>Ricos de Amor</i>",
    list: [
      "Sergio",
      "Dix Pour Cent",
      "The Last Dance",
      "Matchday: FC Barcelona",
      "Chasing Trane",
      "I Called Him Morgan",
      "Miles Davis, Inventor do Cool",
      "3%",
      "Spectros",
      "Axé, canto do Povo de um Lugar",
    ],
  },
  {
    name: "Anavitória",
    profile: "@oanavitoria",
    from: "Músicas que amamos <3",
    list: [
      "Enola Holmes",
      "Peixe Grande e Suas Histórias Maravilhosas",
      "Anne with an E",
      "The OA",
      "Explicando",
      "Lady Bird,A Hora de Voar",
      "Merlí",
      "A Indústria da Cura",
      "Dieta de Gladiadores",
      "",
    ],
  },
  {
    name: "KAIQUE BRITO",
    profile: "@kaiquebritor",
    from: "Dono das dublagens+famosas do TikTok",
    list: [
      "Glee",
      "Stranger Things",
      "One Day at a Time",
      "Anne with an E",
      "A Escolha Perfeita",
      "Greenhouse Academy",
      "Coisa Mais Linda",
      "Jane the Virgin",
      "Alvin e os Esquilos: Na Estrada",
      "iCarly",
    ],
  },
  {
    name: "Bianca Comparato",
    profile: "@biancacomparato",
    from: "Michele em <i>3%</i>",
    list: [
      "Dark",
      "Rainha do Sul",
      "Joias Brutas",
      "Estado Zero",
      "Feito em Casa",
      "Boca a Boca",
      "The Old Guard",
      "Lazzaro Felice",
      "Giri/Haji",
      "3%",
    ],
  },
  {
    name: "Lucas Lucco",
    profile: "@lucaslucco",
    from: "Cantor, compositor e ator",
    list: [
      "Arremesso Final",
      "María Magdalena",
      "Altered Carbon",
      "Explicando",
      "Nada Ortodoxa",
      "Black Mirror",
      "The Old Guard",
      "Vikings",
      "Peaky Blinders",
      "Breaking Bad",
    ],
  },
];
